# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Emojuirity' do
  use_frameworks!

  pod 'KeychainSwift', '~> 7.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'DeviceGuru'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SwiftHash', git: 'https://github.com/onmyway133/SwiftHash'
  pod 'RNCryptor', '~> 5.0'
  pod 'DKCamera'

  target 'EmojuirityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
